# Generated by Django 5.2.8 on 2026-04-06 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='subscription_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
