# Generated by Django 5.2.8 on 2026-04-09 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_sale_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='sale',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='sale',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=14, max_digits=5),
        ),
    ]
