# Generated by Django 5.2.8 on 2026-04-09 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_sale_subtotal_sale_tax_amount_sale_tax_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='subtotal',
        ),
        migrations.AlterField(
            model_name='sale',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
